CREATE TABLE Users (
    UserID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Password VARCHAR2(255) NOT NULL,
    SubscriptionID NUMBER,
    CONSTRAINT fk_users_subscriptions FOREIGN KEY (SubscriptionID) REFERENCES Subscriptions(SubscriptionID)
);

SELECT * FROM Users;

CREATE TABLE Subscriptions (
    SubscriptionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PlanName VARCHAR2(50) NOT NULL,
    Price NUMBER(10, 2) NOT NULL,
    Duration NUMBER NOT NULL, 
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL
);

CREATE TABLE ReadingHistory (
    HistoryID NUMBER PRIMARY KEY, 
    UserID NUMBER NOT NULL,
    BookID NUMBER NOT NULL,
    AccessDate DATE NOT NULL,
    CONSTRAINT fk_readinghistory_users FOREIGN KEY (UserID) REFERENCES Users(UserID),
    CONSTRAINT fk_readinghistory_books FOREIGN KEY (BookID) REFERENCES Books(BookID)
);


CREATE TABLE Transactions (
    TransactionID NUMBER PRIMARY KEY,  
    UserID NUMBER NOT NULL,
    SubscriptionID NUMBER NOT NULL,
    PaymentDate DATE NOT NULL,
    Amount NUMBER(10, 2) NOT NULL,  
    CONSTRAINT fk_transactions_users FOREIGN KEY (UserID) REFERENCES Users(UserID),
    CONSTRAINT fk_transactions_subscriptions FOREIGN KEY (SubscriptionID) REFERENCES Subscriptions(SubscriptionID)
);

CREATE TABLE Books (
    BookID NUMBER PRIMARY KEY, 
    Title VARCHAR2(200) NOT NULL,
    Author VARCHAR2(100) NOT NULL,
    Genre VARCHAR2(50),
    Availability NUMBER(1) DEFAULT 1 CHECK (Availability IN (0, 1)) 
);


DESCRIBE Users

SELECT value FROM v$parameter WHERE name = 'service_names';

